version: 1
services:
  - type: web
    name: your-app-name
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    repo: https://github.com/imado27/bot-tm
    branch: master
